import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PageContentRenderer from "@/components/PageContentRenderer";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "HomveraX Privacy Policy — how we collect, use, and protect your personal data.",
};

const DEFAULT_HTML = `<div class="space-y-8 text-muted-foreground leading-relaxed">
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">1. Information We Collect</h2>
    <p>We collect information you provide directly (name, email, phone, BVN for verification), information generated by using our services (listing activity, messages, transaction history), and automatically collected data (device info, IP address, usage patterns via Firebase Analytics).</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">2. How We Use Your Information</h2>
    <p>We use your information to: operate and improve the Platform, verify identities and process escrow transactions, send notifications about your listings and bookings, provide customer support, detect and prevent fraud, and comply with Nigerian legal requirements.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">3. BVN and NIN Data</h2>
    <p>BVN and NIN data submitted for verification is encrypted at rest and in transit. It is only accessed by authorised HomveraX staff for the purpose of identity verification. We do not sell, share, or use this data for any other purpose.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">4. Data Sharing</h2>
    <p>We do not sell your personal data. We may share data with: payment processors (Paystack/Flutterwave) to process transactions, identity verification partners, law enforcement when legally required, and Google Firebase as our infrastructure provider.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">5. Data Security</h2>
    <p>We use Google Firebase's enterprise-grade security infrastructure, TLS encryption for all data in transit, and role-based access controls. Despite these measures, no system is 100% secure and we cannot guarantee absolute security.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">6. Your Rights</h2>
    <p>You have the right to: access your personal data, correct inaccurate data, request deletion of your account and data, opt out of marketing communications. Contact privacy@homverax.com to exercise these rights.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">7. Cookies</h2>
    <p>We use essential cookies for authentication and analytics cookies (Firebase Analytics) to understand platform usage. See our Cookie Policy for details.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">8. Data Retention</h2>
    <p>We retain your account data while your account is active. Transaction and escrow records are retained for 7 years as required by Nigerian financial regulations. Deleted accounts are removed within 30 days, except data required for legal compliance.</p>
  </div>
  <div>
    <h2 class="text-lg font-serif font-semibold text-foreground mb-2">9. Contact</h2>
    <p>For privacy enquiries: privacy@homverax.com — or write to: HomveraX Data Privacy, Lagos, Nigeria.</p>
  </div>
</div>`;

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <h1 className="text-4xl font-serif font-bold text-foreground mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground mb-10">Last updated: January 1, 2025</p>
        <PageContentRenderer slug="privacy" defaultHtml={DEFAULT_HTML} />
      </div>
      <Footer />
    </div>
  );
}
