"use client";

/**
 * app/admin/content/page.tsx
 * Admin Content Management — edit public page HTML stored in Firestore
 * collection `page_content/{slug}`.
 *
 * Service arbitration: all Firestore access routed through
 * `getPageContent` / `savePageContent` / `resetPageContent`
 * in `src/services/pageContent.ts`. No `db` imports here.
 */

import { useEffect, useState } from "react";
import {
  getPageContent, savePageContent, resetPageContent,
} from "@/services/pageContent";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ExternalLink, Loader2, RotateCcw, Save, FileText } from "lucide-react";
import { toast } from "sonner";
import Link from "next/link";

// ─── Default HTML strings ─────────────────────────────────────────────────────

const DEFAULTS: Record<string, string> = {
  about: `<div class="space-y-8">
  <div class="bg-card border border-border rounded-2xl p-8">
    <h2 class="text-2xl font-serif font-bold text-foreground mb-4">Our Story</h2>
    <p>HomveraX was born out of frustration with the Nigerian property market. Too many people had lost money to fraudulent agents, fake listings, and unscrupulous landlords. We built HomveraX to change that — a marketplace where every agent is identity-verified, every payment is escrow-protected, and every transaction is transparent.</p>
    <p class="mt-4">We merged the best of two proven platforms — Homvera's elegant property search experience and Tetherng's powerful escrow and agent tools — into one comprehensive marketplace: HomveraX.</p>
  </div>
  <div class="bg-card border border-border rounded-2xl p-8">
    <h2 class="text-2xl font-serif font-bold text-foreground mb-4">Contact Us</h2>
    <p>Email: <a href="mailto:hello@homverax.com" class="text-primary hover:underline">hello@homverax.com</a><br/>We're available Monday – Friday, 9am – 6pm WAT.</p>
  </div>
</div>`,

  privacy: `<div class="space-y-8">
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">1. Information We Collect</h2>
  <p>We collect information you provide directly (name, email, phone, BVN for verification), information generated by using our services (listing activity, messages, transaction history), and automatically collected data (device info, IP address, usage patterns via Firebase Analytics).</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">2. How We Use Your Information</h2>
  <p>We use your information to: operate and improve the Platform, verify identities and process escrow transactions, send notifications about your listings and bookings, provide customer support, detect and prevent fraud, and comply with Nigerian legal requirements.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">3. BVN and NIN Data</h2>
  <p>BVN and NIN data submitted for verification is encrypted at rest and in transit. It is only accessed by authorised HomveraX staff for the purpose of identity verification. We do not sell, share, or use this data for any other purpose.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">4. Data Sharing</h2>
  <p>We do not sell your personal data. We may share data with: payment processors (Paystack/Flutterwave) to process transactions, identity verification partners, law enforcement when legally required, and Google Firebase as our infrastructure provider.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">5. Contact</h2>
  <p>For privacy enquiries: privacy@homverax.com — or write to: HomveraX Data Privacy, Lagos, Nigeria.</p></div>
</div>`,

  terms: `<div class="space-y-8">
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">1. Acceptance</h2>
  <p>By accessing or using HomveraX you agree to be bound by these Terms of Service and all applicable laws and regulations of the Federal Republic of Nigeria.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">2. Use of Platform</h2>
  <p>HomveraX is a marketplace connecting property seekers, landlords, and agents. We do not own any listed properties and are not party to any tenancy or sale agreement except as an escrow agent.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">3. Escrow Payments</h2>
  <p>All escrow transactions are governed by the Escrow Agreement which forms part of these Terms. Funds are released only after both parties confirm the transaction or after the inspection window expires.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">4. Contact</h2>
  <p>Questions: legal@homverax.com</p></div>
</div>`,

  cookies: `<div class="space-y-8">
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">What Are Cookies</h2>
  <p>Cookies are small text files stored on your device when you visit a website. They help us remember your preferences and understand how you use HomveraX.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">Cookies We Use</h2>
  <p><strong>Essential:</strong> Required for authentication and core functionality (Firebase Auth session cookie).<br/><strong>Analytics:</strong> Firebase Analytics to understand usage patterns. No personally identifiable information is shared with advertisers.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">Managing Cookies</h2>
  <p>You can disable cookies in your browser settings. Disabling essential cookies will prevent you from logging in.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">Contact</h2>
  <p>Cookie questions: privacy@homverax.com</p></div>
</div>`,

  contact: `<div class="space-y-6">
  <div class="bg-card border border-border rounded-2xl p-8">
    <h2 class="text-xl font-serif font-bold text-foreground mb-4">Get In Touch</h2>
    <p>Email: <a href="mailto:hello@homverax.com" class="text-primary hover:underline">hello@homverax.com</a></p>
    <p class="mt-2">Response time: within 24 hours, Monday – Friday 9am – 6pm WAT.</p>
  </div>
  <div class="bg-card border border-border rounded-2xl p-8">
    <h2 class="text-xl font-serif font-bold text-foreground mb-4">Office</h2>
    <p>Lagos & Abuja, Nigeria</p>
  </div>
</div>`,

  "escrow-agreement": `<div class="space-y-8">
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">1. What Is Escrow?</h2>
  <p>HomveraX acts as a neutral escrow agent, holding your payment securely until both parties confirm the transaction is complete or the inspection window closes.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">2. How It Works</h2>
  <p>Buyer sends payment → HomveraX holds funds → Inspection period starts → Buyer confirms or raises dispute → Funds released to seller or refunded to buyer.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">3. Platform Fee</h2>
  <p>A platform service fee is deducted from the escrow amount at the time of release. The fee percentage is shown before payment is made.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">4. Disputes</h2>
  <p>Either party may raise a dispute within the inspection window. HomveraX will review evidence submitted by both parties and make a final determination within the dispute auto-resolve window.</p></div>
  <div><h2 class="text-lg font-serif font-semibold text-foreground mb-2">5. Contact</h2>
  <p>Escrow support: escrow@homverax.com</p></div>
</div>`,
};

const PAGE_META: { slug: string; label: string; path: string }[] = [
  { slug: "about",            label: "About Us",         path: "/about" },
  { slug: "privacy",          label: "Privacy Policy",   path: "/privacy" },
  { slug: "terms",            label: "Terms of Service", path: "/terms" },
  { slug: "cookies",          label: "Cookie Policy",    path: "/cookies" },
  { slug: "contact",          label: "Contact",          path: "/contact" },
  { slug: "escrow-agreement", label: "Escrow Agreement", path: "/escrow-agreement" },
];

// ─── Types ────────────────────────────────────────────────────────────────────

interface PageState {
  html: string | null; // null = using default
  loading: boolean;
  editing: boolean;
  draft: string;
  saving: boolean;
  resetting: boolean;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function AdminContentPage() {
  const [pages, setPages] = useState<Record<string, PageState>>(() =>
    Object.fromEntries(
      PAGE_META.map(({ slug }) => [slug, {
        html: null, loading: true, editing: false,
        draft: "", saving: false, resetting: false,
      }])
    )
  );

  // Load all pages via service layer
  useEffect(() => {
    PAGE_META.forEach(async ({ slug }) => {
      try {
        const html = await getPageContent(slug);
        setPages((prev) => ({
          ...prev,
          [slug]: { ...prev[slug], html, loading: false },
        }));
      } catch {
        setPages((prev) => ({
          ...prev,
          [slug]: { ...prev[slug], loading: false },
        }));
      }
    });
  }, []);

  const patch = (slug: string, update: Partial<PageState>) =>
    setPages((prev) => ({ ...prev, [slug]: { ...prev[slug], ...update } }));

  const openEditor = (slug: string) => {
    const current = pages[slug];
    patch(slug, {
      editing: true,
      draft: current.html ?? DEFAULTS[slug] ?? "",
    });
  };

  const cancelEditor = (slug: string) => patch(slug, { editing: false, draft: "" });

  const handleSave = async (slug: string) => {
    patch(slug, { saving: true });
    try {
      await savePageContent(slug, pages[slug].draft);
      patch(slug, { html: pages[slug].draft, editing: false, saving: false, draft: "" });
      toast.success("Page saved");
    } catch {
      patch(slug, { saving: false });
      toast.error("Failed to save page");
    }
  };

  const handleReset = async (slug: string) => {
    patch(slug, { resetting: true });
    try {
      await resetPageContent(slug);
      patch(slug, { html: null, editing: false, resetting: false, draft: "" });
      toast.success("Reset to default");
    } catch {
      patch(slug, { resetting: false });
      toast.error("Failed to reset");
    }
  };

  return (
    <DashboardLayout>
      <div className="mb-8">
        <h1 className="text-2xl font-serif font-bold text-foreground">Content Management</h1>
        <p className="text-muted-foreground mt-1 text-sm">
          Edit public page content without code changes. Saved content is served from Firestore;
          reset reverts to the built-in default.
        </p>
      </div>

      <div className="space-y-4">
        {PAGE_META.map(({ slug, label, path }) => {
          const state = pages[slug];
          const isCustom = !!state?.html;

          return (
            <div key={slug} className="bg-card border border-border rounded-2xl overflow-hidden">
              {/* Header row */}
              <div className="flex items-center justify-between gap-4 px-6 py-4 border-b border-border bg-secondary/30">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                    <FileText className="w-4 h-4 text-primary" />
                  </div>
                  <div>
                    <p className="font-medium text-foreground text-sm">{label}</p>
                    <p className="text-xs text-muted-foreground">/page_content/{slug}</p>
                  </div>
                  <Badge variant={isCustom ? "default" : "secondary"} className="text-xs ml-2">
                    {state?.loading ? "loading…" : isCustom ? "custom" : "default"}
                  </Badge>
                </div>
                <div className="flex items-center gap-2">
                  <Link href={path} target="_blank">
                    <Button variant="ghost" size="sm" className="gap-1.5 text-xs">
                      <ExternalLink className="w-3.5 h-3.5" /> Preview
                    </Button>
                  </Link>
                  {isCustom && !state?.editing && (
                    <Button
                      variant="ghost" size="sm"
                      className="gap-1.5 text-xs text-destructive hover:text-destructive"
                      disabled={state?.resetting}
                      onClick={() => handleReset(slug)}
                    >
                      {state?.resetting
                        ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                        : <RotateCcw className="w-3.5 h-3.5" />}
                      Reset to Default
                    </Button>
                  )}
                  {!state?.editing ? (
                    <Button size="sm" className="gap-1.5 text-xs" onClick={() => openEditor(slug)}>
                      Edit
                    </Button>
                  ) : (
                    <>
                      <Button
                        variant="ghost" size="sm" className="text-xs"
                        onClick={() => cancelEditor(slug)}
                        disabled={state.saving}
                      >
                        Cancel
                      </Button>
                      <Button
                        size="sm" className="gap-1.5 text-xs"
                        onClick={() => handleSave(slug)}
                        disabled={state.saving}
                      >
                        {state.saving
                          ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                          : <Save className="w-3.5 h-3.5" />}
                        Save
                      </Button>
                    </>
                  )}
                </div>
              </div>

              {/* Inline editor */}
              {state?.editing && (
                <div className="p-6 space-y-3">
                  <p className="text-xs text-muted-foreground">
                    Edit raw HTML. Use Tailwind classes — they're available on the public pages.
                  </p>
                  <Textarea
                    value={state.draft}
                    onChange={(e) => patch(slug, { draft: e.target.value })}
                    className="font-mono text-xs min-h-[320px] resize-y"
                    spellCheck={false}
                  />
                </div>
              )}
            </div>
          );
        })}
      </div>
    </DashboardLayout>
  );
}
